name: steps_counter_app
description: "Professional Step Counter App with Daily Goals and Analytics"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  
  # For step counting and fitness tracking
  pedometer: ^4.0.2
  permission_handler: ^11.3.1
  
  # For local storage and data persistence
  shared_preferences: ^2.2.3
  sqflite: ^2.3.0
  path: ^1.9.0
  
  # For charts and graphs
  fl_chart: ^0.68.0
  
  # For notifications
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  
  # For date and time formatting
  intl: ^0.19.0
  
  # For state management
  provider: ^6.1.2
  
  # For animations
  lottie: ^3.1.2
  animations: ^2.0.11
  
  # For theming and UI
  flutter_colorpicker: ^1.1.0
  google_fonts: ^6.2.1
  
  # For path/icons
  path_provider: ^2.1.4
  flutter_svg: ^2.0.10+1
  
  # For device info
  device_info_plus: ^10.1.2
  
  # For weather API (optional)
  http: ^1.2.2
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
