// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHlcWcTxJjP5uKfiodEh6ppBSK6aFsjWs',
    appId: '1:472065356722:web:2475863d31f9441a9a6aab',
    messagingSenderId: '472065356722',
    projectId: 'stepcount-9d910',
    authDomain: 'stepcount-9d910.firebaseapp.com',
    storageBucket: 'stepcount-9d910.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDruutSHk6EZ3VQPdDZSoa-rsw3fg3CwLw',
    appId: '1:472065356722:android:1e61724f9c44ce279a6aab',
    messagingSenderId: '472065356722',
    projectId: 'stepcount-9d910',
    storageBucket: 'stepcount-9d910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmV1muIbC2bZlZF9hb-7gUQ-6xjsWCW_A',
    appId: '1:472065356722:ios:ab3b6acd4696503c9a6aab',
    messagingSenderId: '472065356722',
    projectId: 'stepcount-9d910',
    storageBucket: 'stepcount-9d910.firebasestorage.app',
    iosClientId: '472065356722-59qs95qnmrcctffljk1t2s806pgh6e5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepsConterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmV1muIbC2bZlZF9hb-7gUQ-6xjsWCW_A',
    appId: '1:472065356722:ios:ab3b6acd4696503c9a6aab',
    messagingSenderId: '472065356722',
    projectId: 'stepcount-9d910',
    storageBucket: 'stepcount-9d910.firebasestorage.app',
    iosClientId: '472065356722-59qs95qnmrcctffljk1t2s806pgh6e5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepsConterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHlcWcTxJjP5uKfiodEh6ppBSK6aFsjWs',
    appId: '1:472065356722:web:6e9602d3146b70ed9a6aab',
    messagingSenderId: '472065356722',
    projectId: 'stepcount-9d910',
    authDomain: 'stepcount-9d910.firebaseapp.com',
    storageBucket: 'stepcount-9d910.firebasestorage.app',
  );

}